
server:
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
    port-header: X-Forwarded-Port
  use-forward-headers: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: image/png,image/jpeg,image/jpg,application/json,application/xml,text/html,text/css,text/plain,application/javascript
spring:
  thymeleaf:
      mode: LEGACYHTML5
      cache: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#      邮箱配置
  profiles:
    active: dev

mybatis:
  type-aliases-package: com.xyxz.serviceuser.model
  mapper-locations: classpath:mapper/*.xml
multipart:
   maxFileSize: 100Mb
   maxRequestSize: 150Mb